[defaults]
# Default SSO session (matches a [sso-session ...] entry in ~/.aws/config)
sso_session = "perch"

[aliases.dev]
account_id = "327990815300"
default_role = "admin"
roles = ["admin", "developer", "read"]
region = "us-east-1"
kube_context = "perch-dev"
profile_by_role = { admin = "perch-dev-admin", developer = "perch-dev", read = "perch-dev-read" }

[aliases.prod]
account_id = "013255266724"
default_role = "admin"
roles = ["admin", "read"]
region = "us-east-1"
kube_context = "perch-prod"
profile_by_role = { admin = "perch-prod-admin", read = "perch-prod-read" }

[aliases.preprod]
account_id = "663984590467"
default_role = "admin"
roles = ["admin", "read"]
region = "us-east-1"
kube_context = "perch-preprod"
profile_by_role = { admin = "perch-preprod-admin", read = "perch-preprod-read" }

[aliases.prod-legacy]
account_id = "103736728945"
default_role = "admin"
roles = ["admin", "read"]
region = "us-east-1"
kube_context = "perch-prod-legacy"
profile_by_role = { admin = "perch-prod-legacy-admin", read = "perch-prod-legacy-read" }
