package awslogin

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func detectShell() string {
	if override := strings.TrimSpace(os.Getenv("AWS_LOGIN_SHELL")); override != "" {
		return strings.ToLower(override)
	}
	shell := strings.ToLower(filepath.Base(os.Getenv("SHELL")))
	if shell == "" {
		return "bash"
	}
	return shell
}

func logLine(w io.Writer, message string) {
	fmt.Fprintln(w, message)
}

func commandExists(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func expandPath(path string) string {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			return filepath.Join(home, strings.TrimPrefix(path, "~"))
		}
	}
	return path
}

func stripNonDigits(input string) string {
	var b strings.Builder
	for _, r := range input {
		if r >= '0' && r <= '9' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func formatExports(creds RoleCredentials, region, profile string) string {
	lines := []string{}
	if profile != "" {
		lines = append(lines, fmt.Sprintf("export AWS_PROFILE=%s", shellQuote(profile)))
	}
	lines = append(lines, fmt.Sprintf("export AWS_REGION=%s", shellQuote(region)))
	lines = append(lines, fmt.Sprintf("export AWS_DEFAULT_REGION=%s", shellQuote(region)))
	lines = append(lines, fmt.Sprintf("export AWS_ACCESS_KEY_ID=%s", shellQuote(creds.AccessKeyID)))
	lines = append(lines, fmt.Sprintf("export AWS_SECRET_ACCESS_KEY=%s", shellQuote(creds.SecretAccessKey)))
	lines = append(lines, fmt.Sprintf("export AWS_SESSION_TOKEN=%s", shellQuote(creds.SessionToken)))
	if creds.Expiration != nil {
		lines = append(lines, fmt.Sprintf("export AWS_SESSION_EXPIRATION=%s", shellQuote(creds.Expiration.Format(time.RFC3339))))
	}
	return strings.Join(lines, "\n")
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	if !strings.ContainsAny(value, " \t\n'\"\\$`!") {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func runIdentityCheck(profileName, region string, w io.Writer) {
	args := []string{"sts", "get-caller-identity", "--output", "json"}
	if region != "" {
		args = append(args, "--region", region)
	}
	if profileName != "" {
		args = append(args, "--profile", profileName)
	}
	cmd := exec.Command("aws", args...)
	output, err := cmd.Output()
	if err != nil {
		logLine(w, "Could not retrieve identity")
		return
	}
	var data struct {
		UserID  string `json:"UserId"`
		Account string `json:"Account"`
		Arn     string `json:"Arn"`
	}
	if err := json.Unmarshal(output, &data); err != nil {
		return
	}
	logLine(w, "📋 Current AWS identity:")
	if data.UserID != "" {
		logLine(w, fmt.Sprintf("UserId: %s", data.UserID))
	}
	if data.Account != "" {
		logLine(w, fmt.Sprintf("Account: %s", data.Account))
	}
	if data.Arn != "" {
		logLine(w, fmt.Sprintf("Arn: %s", data.Arn))
	}
}

// shellInitDir returns the directory where shell init files are stored
func shellInitDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".aws-login", "shell-init"), nil
}

// shellInitFile returns the path to the shell init file for the given shell
func shellInitFile(shell string) (string, error) {
	dir, err := shellInitDir()
	if err != nil {
		return "", err
	}
	switch shell {
	case "fish":
		return filepath.Join(dir, "init.fish"), nil
	case "zsh":
		return filepath.Join(dir, "init.zsh"), nil
	default:
		return filepath.Join(dir, "init.sh"), nil
	}
}

// shellInitTildePath returns the ~/.aws-login/shell-init/init.<ext> path for the
// given shell. Using ~ keeps rc files readable and portable across user accounts.
func shellInitTildePath(shell string) string {
	switch shell {
	case "fish":
		return "~/.aws-login/shell-init/init.fish"
	case "zsh":
		return "~/.aws-login/shell-init/init.zsh"
	default:
		return "~/.aws-login/shell-init/init.sh"
	}
}

// shellInitHookLine returns the line to add to shell rc file for the given shell.
// Tilde expansion in POSIX shells is not subject to word splitting, so the path
// is safe even when $HOME contains spaces.
func shellInitHookLine(shell string) (string, error) {
	return fmt.Sprintf("source %s", shellInitTildePath(shell)), nil
}

// ensureShellInitFiles creates the shell initialization files
func ensureShellInitFiles() error {
	dir, err := shellInitDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	shells := []string{"bash", "zsh", "fish"}
	for _, shell := range shells {
		file, err := shellInitFile(shell)
		if err != nil {
			return err
		}
		content := generateShellInitContent(shell)
		if err := os.WriteFile(file, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

// generateShellInitContent generates the initialization script for a given shell
func generateShellInitContent(shell string) string {
	switch shell {
	case "fish":
		return `# AWS Login shell initialization (fish)
# Generated by aws-login --install

function aws-login
  if test (count $argv) -gt 0
    switch $argv[1]
      case doctor --doctor --version -v --install --uninstall -h --help
        command aws-login $argv
        return $status
    end
  end
  set -l out (command aws-login --set-profile $argv); or return $status
  for line in $out
    if test (string sub -l 7 $line) = "export "
      set -l kv (string sub -s 8 $line)
      set -l parts (string split -m 1 "=" $kv)
      if test (count $parts) -ge 2
        set -gx $parts[1] $parts[2]
      end
    end
  end
end
`
	default:
		// bash and zsh are compatible
		return `# AWS Login shell initialization (bash/zsh)
# Generated by aws-login --install

aws-login() {
  if [ "$#" -gt 0 ]; then
    case "$1" in
      doctor|--doctor|--version|-v|--install|--uninstall|-h|--help)
        command aws-login "$@"
        return
        ;;
    esac
  fi
  local out
  out="$(command aws-login --set-profile "$@")" || return
  eval "$out"
}
`
	}
}

// shellRCFiles returns the list of shell rc files to modify for the given shell
func shellRCFiles(shell string) ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}

	var files []string
	switch shell {
	case "fish":
		files = append(files,
			filepath.Join(home, ".config/fish/config.fish"),
		)
	case "zsh":
		files = append(files,
			filepath.Join(home, ".zshrc"),
			filepath.Join(home, ".zprofile"),
		)
	default:
		// bash
		files = append(files,
			filepath.Join(home, ".bashrc"),
			filepath.Join(home, ".bash_profile"),
		)
	}
	return files, nil
}

// installShellIntegration installs the shell integration (one-time setup)
func installShellIntegration(shell string, w io.Writer) error {
	if err := ensureShellInitFiles(); err != nil {
		return fmt.Errorf("failed to create shell init files: %w", err)
	}

	hookLine, err := shellInitHookLine(shell)
	if err != nil {
		return err
	}

	rcFiles, err := shellRCFiles(shell)
	if err != nil {
		return err
	}

	anyUpdated := false
	for i, rcFile := range rcFiles {
		if _, err := os.Stat(rcFile); os.IsNotExist(err) {
			if i != 0 {
				// Secondary rc file missing — skip silently
				continue
			}
			// Primary rc file missing — create it (and any parent dirs)
			if err := os.MkdirAll(filepath.Dir(rcFile), 0755); err != nil {
				logLine(w, fmt.Sprintf("Warning: Could not create directory for %s: %v", rcFile, err))
				continue
			}
			if err := os.WriteFile(rcFile, []byte(hookLine+"\n"), 0644); err != nil {
				logLine(w, fmt.Sprintf("Warning: Could not create %s: %v", rcFile, err))
				continue
			}
			logLine(w, fmt.Sprintf("✓ Created %s", rcFile))
			anyUpdated = true
			continue
		}

		content, err := os.ReadFile(rcFile)
		if err != nil {
			logLine(w, fmt.Sprintf("Warning: Could not read %s: %v", rcFile, err))
			continue
		}

		contentStr := string(content)
		if strings.Contains(contentStr, hookLine) {
			logLine(w, fmt.Sprintf("Shell integration already installed in %s", rcFile))
			continue
		}

		newContent := strings.TrimRight(contentStr, "\n") + "\n\n" + hookLine + "\n"
		if err := os.WriteFile(rcFile, []byte(newContent), 0644); err != nil {
			logLine(w, fmt.Sprintf("Warning: Could not write to %s: %v", rcFile, err))
			continue
		}

		logLine(w, fmt.Sprintf("✓ Updated %s", rcFile))
		anyUpdated = true
	}

	if !anyUpdated {
		logLine(w, fmt.Sprintf("ℹ️  No rc files were updated. To activate manually, add to your shell config:\n   %s", hookLine))
	}

	logLine(w, "✅ Shell integration installed successfully!")
	logLine(w, fmt.Sprintf("   To activate in your current session: source %s", shellInitTildePath(shell)))
	return nil
}

// uninstallShellIntegration removes the shell integration
func uninstallShellIntegration(shell string, w io.Writer) error {
	hookLine, err := shellInitHookLine(shell)
	if err != nil {
		return err
	}

	rcFiles, err := shellRCFiles(shell)
	if err != nil {
		return err
	}

	for _, rcFile := range rcFiles {
		if _, err := os.Stat(rcFile); os.IsNotExist(err) {
			continue
		}

		content, err := os.ReadFile(rcFile)
		if err != nil {
			logLine(w, fmt.Sprintf("Warning: Could not read %s: %v", rcFile, err))
			continue
		}

		contentStr := string(content)

		// Remove the hook line if present
		if strings.Contains(contentStr, hookLine) {
			newContent := strings.ReplaceAll(contentStr, hookLine+"\n", "")
			newContent = strings.ReplaceAll(newContent, hookLine, "")

			if err := os.WriteFile(rcFile, []byte(newContent), 0644); err != nil {
				logLine(w, fmt.Sprintf("Warning: Could not write to %s: %v", rcFile, err))
				continue
			}

			logLine(w, fmt.Sprintf("✓ Updated %s", rcFile))
		}
	}

	logLine(w, "✅ Shell integration uninstalled successfully!")
	return nil
}
